WRQ-25915: Added custom site icon for sampler app
enactjs/enact pull request #3246
Opened 2024-06-18 11:21 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
In storybook 8, the favicon.ico file available on the nebula server is not loaded. the storybook default icon is rendered.
This is caused by an API change in storybook8

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added custom site icon and updated storybook configuration to load it

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-25915

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))

2024-06-19 13:43 UTC, stanca-pop-lgp requested changes

2024-06-19 13:43 UTC, stanca-pop-lgp commented on packages/sampler/.storybook/manager-head.html
Please add empty line at the end of file.

2024-06-19 14:23 UTC, daniel-stoian-lgp commented on packages/sampler/.storybook/manager-head.html
> +<link rel="shortcut icon" href="/favicon.ico" />
```suggestion
<link rel="shortcut icon" href="/favicon.ico" />

```

2024-06-21 04:27 UTC, MikyungKim approved these changes
LGTM

2024-06-21 04:27 UTC, MikyungKim approved these changes
LGTM

2024-06-21 04:36 UTC, merged